/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sisu.redisfun;
import io.lettuce.core.RedisClient;

public class App {
	public static void main(String[] args) {
        System.out.println("Starting redisfun...");
		RedisClient client = RedisClient.create("redis://localhost");

		Thread ticker1 = new Thread(new Ticker(client));
		Thread taker1 = new Thread(new Taker(client));
		Thread taker2 = new Thread(new Taker(client));

		try {
			ticker1.start();
			taker1.start();
			taker2.start();

			ticker1.join();
		} catch (Exception e) {
			System.err.println(e.getMessage());
		}
		System.out.println("We're done here!");
    }
}
