/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sisu.redisfun;
import io.lettuce.core.RedisClient;

public class App {
	public static void main(String[] args) {
        System.out.println("Starting redisfun...");
		RedisClient client = RedisClient.create("redis://localhost");

		Thread ticker_thread = new Thread(new Ticker(client));
		Thread taker_thread = new Thread(new Taker(client));
		try {
			ticker_thread.start();
			Thread.sleep(3000);
			taker_thread.start();


			ticker_thread.join();
			taker_thread.join();
		} catch (InterruptedException e) {
			System.err.println(e.getMessage());
		}
		System.out.println("We're done here!");
    }
}
