/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.sisu.redisfun;

import org.junit.Test;
import static org.junit.Assert.*;

public class TickerTest {
    @Test public void test() {
		Ticker ticker = new Ticker(null);
        assertNotNull("dumb test for now", ticker);
    }
}
